/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GmSSL */

#ifndef _Included_GmSSL
#define _Included_GmSSL
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GmSSL
 * Method:    symmetricEncrypt
 * Signature: (Ljava/lang/String;I[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_GmSSL_symmetricEncrypt
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     GmSSL
 * Method:    symmetricDecrypt
 * Signature: (Ljava/lang/String;I[B[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_GmSSL_symmetricDecrypt
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     GmSSL
 * Method:    digest
 * Signature: (Ljava/lang/String;I[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_GmSSL_digest
  (JNIEnv *, jobject, jstring, jint, jbyteArray);

/*
 * Class:     GmSSL
 * Method:    mac
 * Signature: (Ljava/lang/String;I[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_GmSSL_mac
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jbyteArray);

/*
 * Class:     GmSSL
 * Method:    sign
 * Signature: (Ljava/lang/String;I[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_GmSSL_sign
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jbyteArray);

/*
 * Class:     GmSSL
 * Method:    verify
 * Signature: (Ljava/lang/String;I[B[B[B)I
 */
JNIEXPORT jint JNICALL Java_GmSSL_verify
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jbyteArray, jbyteArray);

/*
 * Class:     GmSSL
 * Method:    publicKeyEncrypt
 * Signature: (Ljava/lang/String;I[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_GmSSL_publicKeyEncrypt
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jbyteArray);

/*
 * Class:     GmSSL
 * Method:    publicKeyDecrypt
 * Signature: (Ljava/lang/String;I[B[B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_GmSSL_publicKeyDecrypt
  (JNIEnv *, jobject, jstring, jint, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
