/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/ffx.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_FFX,func,0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_FFX,0,reason)

static ERR_STRING_DATA FFX_str_functs[] = {
    {ERR_FUNC(FFX_F_FFX_DECRYPT), "FFX_decrypt"},
    {ERR_FUNC(FFX_F_FFX_ENCRYPT), "FFX_encrypt"},
    {ERR_FUNC(FFX_F_FFX_INIT), "FFX_init"},
    {0, NULL}
};

static ERR_STRING_DATA FFX_str_reasons[] = {
    {ERR_REASON(FFX_R_ENCRYPT_INIT_FAILURE), "encrypt init failure"},
    {ERR_REASON(FFX_R_INVALID_BLOCK_SIZE), "invalid block size"},
    {ERR_REASON(FFX_R_INVALID_CIPHER_MODE), "invalid cipher mode"},
    {ERR_REASON(FFX_R_INVALID_INPUT_DIGIT), "invalid input digit"},
    {ERR_REASON(FFX_R_INVALID_INPUT_LENGTH), "invalid input length"},
    {ERR_REASON(FFX_R_INVALID_TWEAK_LENGTH), "invalid tweak length"},
    {0, NULL}
};

#endif

int ERR_load_FFX_strings(void)
{
#ifndef OPENSSL_NO_ERR

    if (ERR_func_error_string(FFX_str_functs[0].error) == NULL) {
        ERR_load_strings(0, FFX_str_functs);
        ERR_load_strings(0, FFX_str_reasons);
    }
#endif
    return 1;
}
