/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/otp.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_OTP,func,0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_OTP,0,reason)

static ERR_STRING_DATA OTP_str_functs[] = {
    {ERR_FUNC(OTP_F_OTP_GENERATE), "OTP_generate"},
    {0, NULL}
};

static ERR_STRING_DATA OTP_str_reasons[] = {
    {ERR_REASON(OTP_R_CMAC_FAILURE), "cmac failure"},
    {ERR_REASON(OTP_R_INVALID_PARAMS), "invalid params"},
    {0, NULL}
};

#endif

int ERR_load_OTP_strings(void)
{
#ifndef OPENSSL_NO_ERR

    if (ERR_func_error_string(OTP_str_functs[0].error) == NULL) {
        ERR_load_strings(0, OTP_str_functs);
        ERR_load_strings(0, OTP_str_reasons);
    }
#endif
    return 1;
}
