/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include <openssl/err.h>
#include "e_sdf_err.h"

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(0,func,0)
# define ERR_REASON(reason) ERR_PACK(0,0,reason)

static ERR_STRING_DATA ESDF_str_functs[] = {
    {ERR_FUNC(ESDF_F_SDF_OPEN_DEVICE), "sdf_open_device"},
    {ERR_FUNC(ESDF_F_SDF_RAND_BYTES), "sdf_rand_bytes"},
    {0, NULL}
};

static ERR_STRING_DATA ESDF_str_reasons[] = {
    {ERR_REASON(ESDF_R_OPEN_DEVICE_FAILURE), "open device failure"},
    {ERR_REASON(ESDF_R_OPEN_SESSION_FAILURE), "open session failure"},
    {ERR_REASON(ESDF_R_OPERATION_FAILURE), "operation failure"},
    {0, NULL}
};

#endif

#ifdef ESDF_LIB_NAME
static ERR_STRING_DATA ESDF_lib_name[] = {
    {0, ESDF_LIB_NAME},
    {0, NULL}
};
#endif

static int ESDF_lib_error_code = 0;
static int ESDF_error_init = 1;

static int ERR_load_ESDF_strings(void)
{
    if (ESDF_lib_error_code == 0)
        ESDF_lib_error_code = ERR_get_next_error_library();

    if (ESDF_error_init) {
        ESDF_error_init = 0;
#ifndef OPENSSL_NO_ERR
        ERR_load_strings(ESDF_lib_error_code, ESDF_str_functs);
        ERR_load_strings(ESDF_lib_error_code, ESDF_str_reasons);
#endif

#ifdef ESDF_LIB_NAME
        ESDF_lib_name->error = ERR_PACK(ESDF_lib_error_code, 0, 0);
        ERR_load_strings(0, ESDF_lib_name);
#endif
    }
    return 1;
}

static void ERR_unload_ESDF_strings(void)
{
    if (ESDF_error_init == 0) {
#ifndef OPENSSL_NO_ERR
        ERR_unload_strings(ESDF_lib_error_code, ESDF_str_functs);
        ERR_unload_strings(ESDF_lib_error_code, ESDF_str_reasons);
#endif

#ifdef ESDF_LIB_NAME
        ERR_unload_strings(0, ESDF_lib_name);
#endif
        ESDF_error_init = 1;
    }
}

static void ERR_ESDF_error(int function, int reason, char *file, int line)
{
    if (ESDF_lib_error_code == 0)
        ESDF_lib_error_code = ERR_get_next_error_library();
    ERR_PUT_error(ESDF_lib_error_code, function, reason, file, line);
}
