/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2017 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/kdf2.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_KDF2,func,0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_KDF2,0,reason)

static ERR_STRING_DATA KDF2_str_functs[] = {
    {ERR_FUNC(KDF2_F_IBCS_KDF), "ibcs_kdf"},
    {ERR_FUNC(KDF2_F_X963_KDF), "x963_kdf"},
    {0, NULL}
};

static ERR_STRING_DATA KDF2_str_reasons[] = {
    {ERR_REASON(KDF2_R_DIGEST_FAILURE), "digest failure"},
    {0, NULL}
};

#endif

int ERR_load_KDF2_strings(void)
{
#ifndef OPENSSL_NO_ERR

    if (ERR_func_error_string(KDF2_str_functs[0].error) == NULL) {
        ERR_load_strings(0, KDF2_str_functs);
        ERR_load_strings(0, KDF2_str_reasons);
    }
#endif
    return 1;
}
