/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/bfibe.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_BFIBE,func,0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_BFIBE,0,reason)

static ERR_STRING_DATA BFIBE_str_functs[] = {
    {ERR_FUNC(BFIBE_F_BFIBE_DECRYPT), "BFIBE_decrypt"},
    {ERR_FUNC(BFIBE_F_BFIBE_DO_DECRYPT), "BFIBE_do_decrypt"},
    {ERR_FUNC(BFIBE_F_BFIBE_DO_ENCRYPT), "BFIBE_do_encrypt"},
    {ERR_FUNC(BFIBE_F_BFIBE_ENCRYPT), "BFIBE_encrypt"},
    {ERR_FUNC(BFIBE_F_BFIBE_EXTRACT_PRIVATE_KEY),
     "BFIBE_extract_private_key"},
    {ERR_FUNC(BFIBE_F_BFIBE_SETUP), "BFIBE_setup"},
    {0, NULL}
};

static ERR_STRING_DATA BFIBE_str_reasons[] = {
    {ERR_REASON(BFIBE_R_BFIBE_CIPHERTEXT_FAILURE),
     "bfibe ciphertext failure"},
    {ERR_REASON(BFIBE_R_BUFFER_TOO_SMALL), "buffer too small"},
    {ERR_REASON(BFIBE_R_COMPUTE_OUTLEN_FAILURE), "compute outlen failure"},
    {ERR_REASON(BFIBE_R_D2I_FAILURE), "d2i failure"},
    {ERR_REASON(BFIBE_R_DECRYPT_FAILURE), "decrypt failure"},
    {ERR_REASON(BFIBE_R_ENCRYPT_FAILURE), "encrypt failure"},
    {ERR_REASON(BFIBE_R_HASH_BYTES_FAILURE), "hash bytes failure"},
    {ERR_REASON(BFIBE_R_I2D_FAILURE), "i2d failure"},
    {ERR_REASON(BFIBE_R_INVALID_BFIBE_HASHFUNC), "invalid bfibe hashfunc"},
    {ERR_REASON(BFIBE_R_INVALID_CIPHERTEXT), "invalid ciphertext"},
    {ERR_REASON(BFIBE_R_INVALID_TYPE1CURVE), "invalid type1curve"},
    {ERR_REASON(BFIBE_R_KDF_FAILURE), "kdf failure"},
    {ERR_REASON(BFIBE_R_NOT_NAMED_CURVE), "not named curve"},
    {ERR_REASON(BFIBE_R_PARSE_CURVE_FAILURE), "parse curve failure"},
    {ERR_REASON(BFIBE_R_PARSE_MPK_FAILURE), "parse mpk failure"},
    {ERR_REASON(BFIBE_R_PARSE_PAIRING), "parse pairing"},
    {ERR_REASON(BFIBE_R_RAND_FAILURE), "rand failure"},
    {0, NULL}
};

#endif

int ERR_load_BFIBE_strings(void)
{
#ifndef OPENSSL_NO_ERR

    if (ERR_func_error_string(BFIBE_str_functs[0].error) == NULL) {
        ERR_load_strings(0, BFIBE_str_functs);
        ERR_load_strings(0, BFIBE_str_reasons);
    }
#endif
    return 1;
}
