all:
	cc sm2_keygen_demo.c -lgmssl -o sm2_keygen_demo
	cc sm2_private_key_demo.c -lgmssl -o sm2_private_key_demo
	cc sm2_private_key_parse_demo.c -lgmssl -o sm2_private_key_parse_demo
	cc sm2_public_key_demo.c -lgmssl -o sm2_public_key_demo
	cc sm2_sign_demo.c -lgmssl -o sm2_sign_demo
	cc sm2_sign_ctx_demo.c -lgmssl -o sm2_sign_ctx_demo
	cc sm2_encrypt_demo.c -lgmssl -o sm2_encrypt_demo

clear:
	rm -fr sm2_keygen_demo
	rm -fr sm2_private_key_demo
	rm -fr sm2_private_key_parse_demo
	rm -fr sm2_public_key_demo
	rm -fr sm2_sign_demo
	rm -fr sm2_sign_ctx_demo
	rm -fr sm2_encrypt_demo

