/* ====================================================================
 * Copyright (c) 2014 - 2019 The GmSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the GmSSL Project.
 *    (http://gmssl.org/)"
 *
 * 4. The name "GmSSL Project" must not be used to endorse or promote
 *    products derived from this software without prior written
 *    permission. For written permission, please contact
 *    guanzhi1980@gmail.com.
 *
 * 5. Products derived from this software may not be called "GmSSL"
 *    nor may "GmSSL" appear in their names without prior written
 *    permission of the GmSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the GmSSL Project
 *    (http://gmssl.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE GmSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE GmSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 */

#ifndef HEADER_ECRS_H
#define HEADER_ECRS_H

#include <openssl/opensslconf.h>
#ifndef OPENSSL_NO_ECRS

#include <openssl/ec.h>
#include <openssl/evp.h>
#include <openssl/asn1.h>
#include <openssl/asn1t.h>
#include <openssl/stack.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct ECRS_SIG_st ECRS_SIG;
DECLARE_ASN1_FUNCTIONS(ECRS_SIG)

int ECRS_size(const EC_KEY *ec_key, int n);

ECRS_SIG *ECRS_do_sign(const EVP_MD *md, const unsigned char *dgst,
	int dgstlen, STACK_OF(EC_KEY) *pub_keys, EC_KEY *ec_key);

int ECRS_do_verify(const EVP_MD *md, const unsigned char *dgst, int dgstlen,
	const ECRS_SIG *sig, STACK_OF(EC_KEY) *pub_keys);

int ECRS_sign(int type, const unsigned char *dgst, int dgstlen,
	unsigned char *sig, unsigned int *siglen, STACK_OF(EC_KEY) *pub_keys,
	EC_KEY *ec_key);

int ECRS_verify(int type, const unsigned char *dgst, int dgstlen,
	const unsigned char *sig, int siglen, STACK_OF(EC_KEY) *pub_keys);

/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */

int ERR_load_ECRS_strings(void);

/* Error codes for the ECRS functions. */

/* Function codes. */
# define ECRS_F_ECRS_DO_SIGN                              100
# define ECRS_F_ECRS_DO_VERIFY                            103
# define ECRS_F_ECRS_SIGN                                 101
# define ECRS_F_ECRS_VERIFY                               102

/* Reason codes. */
# define ECRS_R_EC_KEY_NOT_MATCH                          100
# define ECRS_R_INVALID_DIGEST_ALGOR                      101
# define ECRS_R_NO_SIGNING_KEY                            102
# define ECRS_R_PARSE_SIGNATURE_FAILURE                   103
# define ECRS_R_PUBLIC_KEYS_NOT_MATCH                     104
# define ECRS_R_PUBLIC_KEYS_NOT_MATCH_SIG                 105

#  ifdef  __cplusplus
}
#  endif
# endif
#endif
