/* ====================================================================
 * Copyright (c) 2015 - 2016 The GmSSL Project.  All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 * 1. Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright
 *    notice, this list of conditions and the following disclaimer in
 *    the documentation and/or other materials provided with the
 *    distribution.
 *
 * 3. All advertising materials mentioning features or use of this
 *    software must display the following acknowledgment:
 *    "This product includes software developed by the GmSSL Project.
 *    (http://gmssl.org/)"
 *
 * 4. The name "GmSSL Project" must not be used to endorse or promote
 *    products derived from this software without prior written
 *    permission. For written permission, please contact
 *    guanzhi1980@gmail.com.
 *
 * 5. Products derived from this software may not be called "GmSSL"
 *    nor may "GmSSL" appear in their names without prior written
 *    permission of the GmSSL Project.
 *
 * 6. Redistributions of any form whatsoever must retain the following
 *    acknowledgment:
 *    "This product includes software developed by the GmSSL Project
 *    (http://gmssl.org/)"
 *
 * THIS SOFTWARE IS PROVIDED BY THE GmSSL PROJECT ``AS IS'' AND ANY
 * EXPRESSED OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 * PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE GmSSL PROJECT OR
 * ITS CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT
 * NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
 * HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,
 * STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
 * OF THE POSSIBILITY OF SUCH DAMAGE.
 * ====================================================================
 */

#ifndef HEADER_GMSKF_H
#define HEADER_GMSKF_H

#include <openssl/sgd.h>
#include <openssl/skf.h>

#ifndef SKF_NO_GMSSL
#define SKF_NO_PADDING		0
#define SKF_PKCS5_PADDING	1
#endif

#ifndef SKF_NO_GMSSL
#define DEV_ABSENT_STATE		0x00000000
#define DEV_PRESENT_STATE		0x00000001
#define DEV_UNKNOW_STATE		0x00000010
#endif

#ifndef SKF_NO_GMSSL
#define CONTAINER_TYPE_UNDEF	0
#define CONTAINER_TYPE_RSA	1
#define CONTAINER_TYPE_ECC	2
#endif

#ifdef __cplusplus
extern "C" {
#endif


//FIXME: change name
const char *SKF_get_alg_name(ULONG ulAlgID);

int SKF_PrintDeviceInfo(FILE *fp, DEVINFO *devInfo);
int SKF_PrintRSAPublicKey(FILE *fp, RSAPUBLICKEYBLOB *pk);
int SKF_PrintRSAPrivateKey(FILE *fp, RSAPRIVATEKEYBLOB *pk);
int SKF_PrintECCPublicKey(FILE *fp, ECCPUBLICKEYBLOB *pk);
int SKF_PrintECCPrivateKey(FILE *fp, ECCPRIVATEKEYBLOB *pk);
int SKF_PrintECCCipher(FILE *fp, ECCCIPHERBLOB *cipher);
int SKF_PrintECCSignature(FILE *fp, ECCSIGNATUREBLOB *sig);
const char *SKF_GetErrorString(ULONG error);



/* BEGIN ERROR CODES */
/*
 * The following lines are auto generated by the script mkerr.pl. Any changes
 * made after this point may be overwritten when the script is next run.
 */

int ERR_load_SKF_strings(void);

/* Error codes for the SKF functions. */

/* Function codes. */
# define SKF_F_SKF_CLOSEHANDLE                            100
# define SKF_F_SKF_DECRYPT                                101
# define SKF_F_SKF_DECRYPTFINAL                           102
# define SKF_F_SKF_DECRYPTINIT                            103
# define SKF_F_SKF_DECRYPTUPDATE                          104
# define SKF_F_SKF_DIGEST                                 105
# define SKF_F_SKF_DIGESTFINAL                            106
# define SKF_F_SKF_DIGESTINIT                             107
# define SKF_F_SKF_DIGESTUPDATE                           108
# define SKF_F_SKF_ENCRYPT                                109
# define SKF_F_SKF_ENCRYPTFINAL                           110
# define SKF_F_SKF_ENCRYPTINIT                            111
# define SKF_F_SKF_ENCRYPTUPDATE                          112
# define SKF_F_SKF_EXTECCDECRYPT                          113
# define SKF_F_SKF_EXTECCENCRYPT                          114
# define SKF_F_SKF_EXTECCSIGN                             115
# define SKF_F_SKF_EXTECCVERIFY                           116
# define SKF_F_SKF_EXTRSAPRIKEYOPERATION                  117
# define SKF_F_SKF_EXTRSAPUBKEYOPERATION                  118
# define SKF_F_SKF_GENEXTECCKEYPAIR                       119
# define SKF_F_SKF_GENEXTRSAKEY                           120
# define SKF_F_SKF_GENRANDOM                              121
# define SKF_F_SKF_GETDEVINFO                             122
# define SKF_F_SKF_GETDEVSTATE                            123
# define SKF_F_SKF_HANDLE_GET_CBCMAC_CTX                  124
# define SKF_F_SKF_HANDLE_GET_CIPHER                      125
# define SKF_F_SKF_HANDLE_GET_CIPHER_CTX                  126
# define SKF_F_SKF_HANDLE_GET_CMAC_CTX                    134
# define SKF_F_SKF_HANDLE_GET_KEY                         127
# define SKF_F_SKF_HANDLE_GET_MD_CTX                      128
# define SKF_F_SKF_MAC                                    129
# define SKF_F_SKF_MACFINAL                               130
# define SKF_F_SKF_MACINIT                                131
# define SKF_F_SKF_MACUPDATE                              132
# define SKF_F_SKF_SETSYMMKEY                             133

/* Reason codes. */
# define SKF_R_BUFFER_TOO_SMALL                           100
# define SKF_R_CTX_NOT_CREATED                            101
# define SKF_R_DECRYPT_FAILED                             102
# define SKF_R_ENCODE_CIPHERTEXT_FAILED                   103
# define SKF_R_ENCODE_FAILED                              104
# define SKF_R_ENCODE_SIGNATURE_FAILED                    105
# define SKF_R_ENCRYPT_FAILED                             106
# define SKF_R_FAIL                                       107
# define SKF_R_GEN_RSA_FAILED                             108
# define SKF_R_GET_PRIVATE_KEY_FAILED                     109
# define SKF_R_GET_PUBLIC_KEY_FAILED                      110
# define SKF_R_INVALID_ALGID                              111
# define SKF_R_INVALID_ALGOR                              112
# define SKF_R_INVALID_ARGUMENTS                          113
# define SKF_R_INVALID_BLOB                               114
# define SKF_R_INVALID_CIPHERTEXT                         115
# define SKF_R_INVALID_CIPHERTEXT_LENGTH                  116
# define SKF_R_INVALID_CIPHER_CTX_HANDLE                  117
# define SKF_R_INVALID_DIGEST_LENGTH                      118
# define SKF_R_INVALID_ECC_PRIVATE_KEY                    119
# define SKF_R_INVALID_ECC_PUBLIC_KEY                     120
# define SKF_R_INVALID_EC_PRIVATE_KEY                     121
# define SKF_R_INVALID_EC_PUBLIC_KEY                      122
# define SKF_R_INVALID_FEED_BIT_LENGTH                    123
# define SKF_R_INVALID_HANDLE                             124
# define SKF_R_INVALID_HANDLE_ALGOR                       125
# define SKF_R_INVALID_HANDLE_MAGIC                       126
# define SKF_R_INVALID_HANDLE_TYPE                        127
# define SKF_R_INVALID_HASH_HANDLE                        128
# define SKF_R_INVALID_ID_LENGTH                          129
# define SKF_R_INVALID_INPUT_LENGTH                       130
# define SKF_R_INVALID_IV_LENGTH                          131
# define SKF_R_INVALID_KEY_HANDLE                         132
# define SKF_R_INVALID_KEY_LENGTH                         133
# define SKF_R_INVALID_MAC_HANDLE                         134
# define SKF_R_INVALID_PLAINTEXT_LENGTH                   135
# define SKF_R_INVALID_RANDOM_LENGTH                      136
# define SKF_R_INVALID_RSA_PUBLIC_KEY                     137
# define SKF_R_INVALID_SIGNATURE                          138
# define SKF_R_MALLOC_FAILED                              139
# define SKF_R_NO_PUBLIC_KEY                              140
# define SKF_R_NULL_ARGUMENT                              141
# define SKF_R_SIGN_FAILED                                142
# define SKF_R_VERIFY_NOT_PASS                            143

# ifdef  __cplusplus
}
# endif
#endif
