all:
	cc sm9_keygen_demo.c -lgmssl -o sm9_keygen_demo
	cc sm9_sign_demo.c -lgmssl -o sm9_sign_demo
	cc sm9_encrypt_demo.c -lgmssl -o sm9_encrypt_demo

clean:
	rm -fr sm9_keygen_demo
	rm -fr sm9_sign_demo
	rm -fr sm9_encrypt_demo

