/*
 * Generated by util/mkerr.pl DO NOT EDIT
 * Copyright 1995-2016 The OpenSSL Project Authors. All Rights Reserved.
 *
 * Licensed under the OpenSSL license (the "License").  You may not use
 * this file except in compliance with the License.  You can obtain a copy
 * in the file LICENSE in the source distribution or at
 * https://www.openssl.org/source/license.html
 */

#include <stdio.h>
#include <openssl/err.h>
#include <openssl/gmsaf.h>

/* BEGIN ERROR CODES */
#ifndef OPENSSL_NO_ERR

# define ERR_FUNC(func) ERR_PACK(ERR_LIB_SAF,func,0)
# define ERR_REASON(reason) ERR_PACK(ERR_LIB_SAF,0,reason)

static ERR_STRING_DATA SAF_str_functs[] = {
    {ERR_FUNC(SAF_F_SAF_BASE64_CREATEBASE64OBJ),
     "SAF_Base64_CreateBase64Obj"},
    {ERR_FUNC(SAF_F_SAF_BASE64_DECODE), "SAF_Base64_Decode"},
    {ERR_FUNC(SAF_F_SAF_BASE64_DECODEFINAL), "SAF_Base64_DecodeFinal"},
    {ERR_FUNC(SAF_F_SAF_BASE64_DECODEUPDATE), "SAF_Base64_DecodeUpdate"},
    {ERR_FUNC(SAF_F_SAF_BASE64_ENCODE), "SAF_Base64_Encode"},
    {ERR_FUNC(SAF_F_SAF_BASE64_ENCODEFINAL), "SAF_Base64_EncodeFinal"},
    {ERR_FUNC(SAF_F_SAF_BASE64_ENCODEUPDATE), "SAF_Base64_EncodeUpdate"},
    {ERR_FUNC(SAF_F_SAF_CREATESYMMKEYOBJ), "SAF_CreateSymmKeyObj"},
    {ERR_FUNC(SAF_F_SAF_ECCPUBLICKEYENC), "SAF_EccPublicKeyEnc"},
    {ERR_FUNC(SAF_F_SAF_ECCPUBLICKEYENCBYCERT), "SAF_EccPublicKeyEncByCert"},
    {ERR_FUNC(SAF_F_SAF_ECCSIGN), "SAF_EccSign"},
    {ERR_FUNC(SAF_F_SAF_ECCVERIFYSIGN), "SAF_EccVerifySign"},
    {ERR_FUNC(SAF_F_SAF_ECCVERIFYSIGNBYCERT), "SAF_EccVerifySignByCert"},
    {ERR_FUNC(SAF_F_SAF_GENECCKEYPAIR), "SAF_GenEccKeyPair"},
    {ERR_FUNC(SAF_F_SAF_GENERATEAGREEMENTDATAWITHECC),
     "SAF_GenerateAgreementDataWithECC"},
    {ERR_FUNC(SAF_F_SAF_GENERATEKEYWITHECC), "SAF_GenerateKeyWithECC"},
    {ERR_FUNC(SAF_F_SAF_GETECCPUBLICKEY), "SAF_GetEccPublicKey"},
    {ERR_FUNC(SAF_F_SAF_MACFINAL), "SAF_MacFinal"},
    {ERR_FUNC(SAF_F_SAF_MACUPDATE), "SAF_MacUpdate"},
    {ERR_FUNC(SAF_F_SAF_PKCS7_DECODEDIGESTEDDATA),
     "SAF_Pkcs7_DecodeDigestedData"},
    {ERR_FUNC(SAF_F_SAF_PKCS7_ENCODEDIGESTEDDATA),
     "SAF_Pkcs7_EncodeDigestedData"},
    {ERR_FUNC(SAF_F_SAF_SYMMDECRYPTUPDATE), "SAF_SymmDecryptUpdate"},
    {ERR_FUNC(SAF_F_SAF_SYMMENCRYPTUPDATE), "SAF_SymmEncryptUpdate"},
    {0, NULL}
};

static ERR_STRING_DATA SAF_str_reasons[] = {
    {ERR_REASON(SAF_R_BUFFER_TOO_SMALL), "buffer too small"},
    {ERR_REASON(SAF_R_CBCMAC_FAILURE), "cbcmac failure"},
    {ERR_REASON(SAF_R_GEN_RANDOM), "gen random"},
    {ERR_REASON(SAF_R_INT_OVERFLOW), "int overflow"},
    {ERR_REASON(SAF_R_INVALID_ALGOR), "invalid algor"},
    {ERR_REASON(SAF_R_INVALID_CONTEXT), "invalid context"},
    {ERR_REASON(SAF_R_INVALID_DIGEST_ALGOR), "invalid digest algor"},
    {ERR_REASON(SAF_R_INVALID_HANDLE), "invalid handle"},
    {ERR_REASON(SAF_R_INVALID_INPUT_LENGTH), "invalid input length"},
    {ERR_REASON(SAF_R_INVALID_KEY_LENGTH), "invalid key length"},
    {ERR_REASON(SAF_R_INVALID_KEY_USAGE), "invalid key usage"},
    {ERR_REASON(SAF_R_INVALID_LENGTH), "invalid length"},
    {ERR_REASON(SAF_R_MAC_FAILURE), "mac failure"},
    {ERR_REASON(SAF_R_OPERATION_NOT_INITIALIZED),
     "operation not initialized"},
    {ERR_REASON(SAF_R_SAF_ERROR), "saf error"},
    {0, NULL}
};

#endif

int ERR_load_SAF_strings(void)
{
#ifndef OPENSSL_NO_ERR

    if (ERR_func_error_string(SAF_str_functs[0].error) == NULL) {
        ERR_load_strings(0, SAF_str_functs);
        ERR_load_strings(0, SAF_str_reasons);
    }
#endif
    return 1;
}
