name: MSVC CMake

on:
  push:
    branches: [ "master", "v2.5" ]
  pull_request:
    branches: [ "master" ]
  schedule:
    - cron: '41 2 * * 4'

env:
  # Path to the CMake build directory.
  build: '${{ github.workspace }}/build'

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: read
    name: Build
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure CMake
        run: cmake -B ${{ env.build }}

      - name: Build CMake
        run: cmake --build ${{ env.build }}
